from collections.abc import AsyncIterable, Awaitable, Callable, Iterable, Mapping
from typing import Any, AsyncContextManager, Literal

HeaderInput = Mapping[str, str] | Iterable[tuple[str, str]] | None
BodyInput = str | bytes | bytearray | memoryview | Iterable[bytes] | AsyncIterable[bytes] | None
Scope = Literal['loopback', 'internal', 'external']
class DhttpError(RuntimeError):
    code: str
    protocol_code: int | None
class Headers:
    def __init__(self, pairs: HeaderInput = ...) -> None: ...
    def items(self) -> list[tuple[str, str]]: ...
    def get(self, name: str, default: str | None = ...) -> str | None: ...
    def getall(self, name: str) -> list[str]: ...
class Authority:
    name: str
    certificates: list[bytes]
    public_key: bytes
    owner_hash: str
    subject_key_identifier: bytes
    def verify(self, data: bytes, signature: bytes) -> bool: ...
class LocalAuthority(Authority):
    async def sign(self, data: bytes) -> bytes: ...
class ClientResponse:
    status: int
    headers: Headers
    remote_authority: Authority | None
    content: AsyncIterable[bytes]
    async def read(self) -> bytes: ...
    async def text(self, encoding: str = ...) -> str: ...
    async def json(self) -> Any: ...
    async def trailers(self) -> Headers: ...
    async def release(self) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> ClientResponse: ...
    async def __aexit__(self, *args: Any) -> None: ...
class ServerRequest:
    local_authority: LocalAuthority
    method: str
    url: str
    headers: Headers
    remote_authority: Authority | None
    content: AsyncIterable[bytes]
    async def read(self) -> bytes: ...
    async def text(self, encoding: str = ...) -> str: ...
    async def json(self) -> Any: ...
    async def trailers(self) -> Headers: ...
class Response:
    body: BodyInput
    status: int
    headers: Headers
    def __init__(self, body: BodyInput = ..., *, status: int = ..., headers: HeaderInput = ..., trailers: Any = ...) -> None: ...
    @classmethod
    def text(cls, text: str, *, status: int = ..., headers: HeaderInput = ..., encoding: str = ...) -> Response: ...
    @classmethod
    def json(cls, data: Any, *, status: int = ..., headers: HeaderInput = ...) -> Response: ...
class _RequestContext(Awaitable[ClientResponse], AsyncContextManager[ClientResponse]): ...
class Listener:
    async def close(self) -> None: ...
    async def __aenter__(self) -> Listener: ...
    async def __aexit__(self, *args: Any) -> None: ...
class Endpoint:
    name: str | None
    @classmethod
    async def load(cls, name: str) -> Endpoint: ...
    @classmethod
    async def load_from(cls, path: str) -> Endpoint: ...
    async def local_authority(self) -> LocalAuthority | None: ...
    async def reload(self) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Endpoint: ...
    async def __aexit__(self, *args: Any) -> None: ...
    def request(self, method: str, url: str, *, headers: HeaderInput = ..., data: BodyInput = ..., json: Any = ..., trailers: Any = ..., timeout: float | None = ..., owner_hash: str | None = ...) -> _RequestContext: ...
    def get(self, url: str, **options: Any) -> _RequestContext: ...
    def head(self, url: str, **options: Any) -> _RequestContext: ...
    def post(self, url: str, **options: Any) -> _RequestContext: ...
    def put(self, url: str, **options: Any) -> _RequestContext: ...
    def patch(self, url: str, **options: Any) -> _RequestContext: ...
    def delete(self, url: str, **options: Any) -> _RequestContext: ...
    def options(self, url: str, **options: Any) -> _RequestContext: ...
    async def listen(self, scopes: Iterable[Scope], handler: Callable[[ServerRequest], Response | Awaitable[Response]]) -> Listener: ...
Anonymous: Endpoint
async def init(*, peers: Mapping[str, str] | Iterable[tuple[str, str]] | None = ..., root_certificates: bytes | None = ...) -> None: ...
def addresses() -> list[str]: ...
def json_response(data: Any, *, status: int = ..., headers: HeaderInput = ...) -> Response: ...
