use std::{env, fs, path::PathBuf};

const ROOT_CA_ENV: &str = "DHTTP_ROOT_CA";
const BOOTSTRAP_URL_ENV: &str = "DHTTP_BOOTSTRAP_URL";

const DEFAULT_BOOTSTRAP_URL: &str = "https://bootstrap.genmeta.net:20002";
const DEFAULT_ROOT_CA_PEM: &str = "\
-----BEGIN CERTIFICATE-----\n\
MIICVzCCAd2gAwIBAgIUe8kwBACY6f+MAzdCBVPmq4p+CiswCgYIKoZIzj0EAwMw\n\
WTELMAkGA1UEBhMCQ04xETAPBgNVBAgMCEhvbmdLb25nMRwwGgYDVQQKDBNHZW5t\n\
ZXRhIEVDQyBSb290IENBMRkwFwYDVQQDDBByb290Lmdlbm1ldGEubmV0MB4XDTI2\n\
MDcxMzEzMDQyOFoXDTQ2MDcxMzEzMDQyOFowWTELMAkGA1UEBhMCQ04xETAPBgNV\n\
BAgMCEhvbmdLb25nMRwwGgYDVQQKDBNHZW5tZXRhIEVDQyBSb290IENBMRkwFwYD\n\
VQQDDBByb290Lmdlbm1ldGEubmV0MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEO+zm\n\
ZYL0LaqTKf7mW4tnRWeNop1p8f2ZsexhAl23GHkHwLjCihhQzBCZ8VMRPAdVcEIS\n\
XcGY/U6+Z1IAYCRG0tdsUCXHXxzvDY0I9FZqZw1Xo94gkHnNe7mTu/jCQg3Xo2Yw\n\
ZDAdBgNVHQ4EFgQUq1SsSWDnp0G5v5/hWi9CC7eWDTwwHwYDVR0jBBgwFoAUq1Ss\n\
SWDnp0G5v5/hWi9CC7eWDTwwEgYDVR0TAQH/BAgwBgEB/wIBATAOBgNVHQ8BAf8E\n\
BAMCAQYwCgYIKoZIzj0EAwMDaAAwZQIwK9GqxdmRHJw7iB0z/b/WgzBv2jb7OmFS\n\
uVPA+6ZNApjYXCZUOVQFC60KUUV7yW53AjEA5lLrdXxdGNSIuLe1h/A+v/vRrYtt\n\
132Jzh+LkKBHdC1wcvDKjk2ZQG5WySly6VMp\n\
-----END CERTIFICATE-----\n";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let root_ca_dest = out_dir.join("root.crt");
    let root_ca = root_ca_bytes();
    fs::write(&root_ca_dest, &root_ca).unwrap_or_else(|error| {
        panic!(
            "failed to write generated DHTTP root CA to {}: {error}",
            root_ca_dest.display()
        )
    });

    let bootstrap_url = env_or_default(BOOTSTRAP_URL_ENV, DEFAULT_BOOTSTRAP_URL);
    let bootstrap_authority = bootstrap_authority(&bootstrap_url).unwrap_or_else(|error| {
        panic!("invalid {BOOTSTRAP_URL_ENV} value {bootstrap_url:?}: {error}")
    });
    let bootstrap = format!(
        "// @generated by build.rs; do not edit.\n\
         pub const DHTTP_BOOTSTRAP_URL: &str = {bootstrap_url:?};\n\
         pub const DHTTP_BOOTSTRAP_AUTHORITY: &str = {bootstrap_authority:?};\n\
         pub const DHTTP_ROOT_CA: &[u8] = &{root_ca:?};\n"
    );
    fs::write(out_dir.join("bootstrap.rs"), bootstrap)
        .expect("failed to write generated DHTTP bootstrap constants");

    println!("cargo::rerun-if-env-changed={ROOT_CA_ENV}");
    println!("cargo::rerun-if-env-changed={BOOTSTRAP_URL_ENV}");
    if let Some(root_ca) = optional_env_path(ROOT_CA_ENV) {
        println!("cargo::rerun-if-changed={}", root_ca.display());
    }
}

fn env_or_default(name: &str, default: &str) -> String {
    env::var(name).unwrap_or_else(|_| default.to_owned())
}

fn bootstrap_authority(value: &str) -> Result<String, String> {
    let url = url::Url::parse(value).map_err(|error| error.to_string())?;
    if url.scheme() != "https" {
        return Err("scheme must be https".to_owned());
    }
    if url.username() != "" || url.password().is_some() {
        return Err("credentials are not allowed".to_owned());
    }
    if url.path() != "/" || url.query().is_some() || url.fragment().is_some() {
        return Err("path, query, and fragment are not allowed".to_owned());
    }

    let host = url
        .host_str()
        .ok_or_else(|| "host is required".to_owned())?;
    let port = url
        .port()
        .ok_or_else(|| "an explicit port is required".to_owned())?;
    if matches!(url.host(), Some(url::Host::Ipv6(_))) {
        Ok(format!("[{host}]:{port}"))
    } else {
        Ok(format!("{host}:{port}"))
    }
}

fn optional_env_path(name: &str) -> Option<PathBuf> {
    env::var_os(name).map(PathBuf::from)
}

fn root_ca_bytes() -> Vec<u8> {
    let Some(root_ca) = optional_env_path(ROOT_CA_ENV) else {
        return DEFAULT_ROOT_CA_PEM.as_bytes().to_vec();
    };

    fs::read(&root_ca).unwrap_or_else(|error| {
        panic!(
            "failed to read DHTTP root CA from {}: {error}",
            root_ca.display()
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_bootstrap_env_uses_genmeta_production_default() {
        let name = format!("__DHTTP_MISSING_BOOTSTRAP_{}", std::process::id());

        assert_eq!(
            env_or_default(&name, DEFAULT_BOOTSTRAP_URL),
            "https://bootstrap.genmeta.net:20002"
        );
    }

    #[test]
    fn bootstrap_url_produces_stun_authority() {
        assert_eq!(
            bootstrap_authority("https://bootstrap.genmeta.net:20002").as_deref(),
            Ok("bootstrap.genmeta.net:20002")
        );
    }

    #[test]
    fn bootstrap_url_requires_https_and_explicit_port() {
        assert!(bootstrap_authority("http://bootstrap.genmeta.net:20002").is_err());
        assert!(bootstrap_authority("https://bootstrap.genmeta.net").is_err());
    }

    #[test]
    fn default_root_ca_is_pem_certificate() {
        assert!(DEFAULT_ROOT_CA_PEM.starts_with("-----BEGIN CERTIFICATE-----"));
        assert!(DEFAULT_ROOT_CA_PEM.ends_with("-----END CERTIFICATE-----\n"));
    }
}
