mod bootstrap_config;

use std::{env, fs, path::PathBuf};

use bootstrap_config::{
    DEFAULT_BOOTSTRAP_URL, DEFAULT_ROOT_CA_PEM, bootstrap_authority, env_or_default,
    parse_root_ca_der,
};

const ROOT_CA_PEM_ENV: &str = "DHTTP_ROOT_CA_PEM";
const BOOTSTRAP_URL_ENV: &str = "DHTTP_BOOTSTRAP_URL";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let root_ca_der = root_ca_der();

    let bootstrap_url = env_or_default(BOOTSTRAP_URL_ENV, DEFAULT_BOOTSTRAP_URL);
    let bootstrap_authority = bootstrap_authority(&bootstrap_url).unwrap_or_else(|error| {
        panic!("invalid {BOOTSTRAP_URL_ENV} value {bootstrap_url:?}: {error}")
    });
    let bootstrap = format!(
        "// @generated by build.rs; do not edit.\n\
         pub const DHTTP_BOOTSTRAP_URL: &str = {bootstrap_url:?};\n\
         pub const DHTTP_BOOTSTRAP_AUTHORITY: &str = {bootstrap_authority:?};\n\
         pub const DHTTP_ROOT_CA_DER: &[u8] = &{root_ca_der:?};\n"
    );
    fs::write(out_dir.join("bootstrap.rs"), bootstrap)
        .expect("failed to write generated DHTTP bootstrap constants");

    println!("cargo::rerun-if-env-changed={ROOT_CA_PEM_ENV}");
    println!("cargo::rerun-if-env-changed={BOOTSTRAP_URL_ENV}");
}

fn root_ca_der() -> Vec<u8> {
    let pem = match env::var(ROOT_CA_PEM_ENV) {
        Ok(pem) => pem,
        Err(env::VarError::NotPresent) => DEFAULT_ROOT_CA_PEM.to_owned(),
        Err(env::VarError::NotUnicode(_)) => {
            panic!("{ROOT_CA_PEM_ENV} must contain UTF-8 PEM text")
        }
    };

    parse_root_ca_der(&pem).unwrap_or_else(|error| panic!("invalid {ROOT_CA_PEM_ENV}: {error}"))
}
