[package]
name = "dhttp"
version.workspace = true
edition.workspace = true

[dependencies]
bon = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
snafu = { workspace = true }
tower-service = { workspace = true }
dhttp-identity = { workspace = true }
home = { workspace = true }
ddns = { workspace = true }
h3x = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
