[package]
name = "dhttp"
description = "Rust SDK for building DHTTP endpoints"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bon = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
matchit = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
snafu = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tower-service = { workspace = true }
tracing = { workspace = true }
dhttp-identity = { workspace = true }
dhttp-home = { workspace = true }
ddns = { workspace = true }
h3x = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
