[package]
name = "dhttp"
description = "The True Internet"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/dhttp.rs"

[features]
default = []
access = ["dep:dhttp-access"]
log = ["dep:dhttp-log"]
access-cli = ["access", "dhttp-access/cli"]
access-http = ["access", "dhttp-access/http"]
access-orm = ["access", "dhttp-access/orm"]
access-migration = ["access-orm", "dhttp-access/migration"]
access-peg-trace = ["access", "dhttp-access/peg-trace"]

[dependencies]
bytes.workspace = true
futures.workspace = true
dhttp-home.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
h3x.workspace = true
qbase = { workspace = true }
qconn = { workspace = true }
qtransport = { workspace = true }
qprotocol = { workspace = true }
qudp = { path = "../../dquic/qudp" }
qrecovery = { workspace = true }
netdev = { version = "0.46.2", default-features = false }
netwatcher = "0.8"
rustls.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "net", "sync", "rt", "time"] }
tower-service.workspace = true
tracing.workspace = true
tower = { version = "0.5", features = ["util"] }
async-stream = "0.3"
scopeguard = "1"
dhttp-identity = { path = "../identity" }
qtls = { workspace = true }
dhttp-access = { workspace = true, optional = true }
dhttp-log = { workspace = true, optional = true }

[build-dependencies]
rustls-pemfile = "2"
url = "2"
x509-parser.workspace = true

[dev-dependencies]
rcgen = "0.14"
rustls-pemfile = "2"
tokio = { workspace = true, features = ["macros", "rt"] }
url = "2"
x509-parser.workspace = true
