[package]
name = "dhttp-identity"
description = "Identity primitives for DHttp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = { workspace = true }
snafu = { workspace = true }
futures = { workspace = true }
rustls = { workspace = true, features = ["std", "ring"] }
bytes = { workspace = true }
http = { workspace = true }
ring = "0.17"
x509-parser = { workspace = true }

[dev-dependencies]
serde_json = "1"
